### ISSUE TITLE
[problem] not  compatibility with some ui mod

### ISSUE THREAD

**Issue by zeteticl** [Xbozon/storyteller#13]
like Ernie's modern ui
cant show stories text
![image](https://user-images.githubusercontent.com/23254376/143386554-e29d918f-b18a-44fa-9697-ed251c052db3.png)

cant show background image
![image](https://user-images.githubusercontent.com/23254376/143386623-89930ae7-3ffb-4669-adde-0c1cc04a8f5c.png)

**Comment by Xbozon** [comment]
@zeteticl Starting to deal with this problem this week.

**Comment by Xbozon** [comment]
@zeteticl I apologize for the wait, the transition to version v9 has been difficult. Fixed in version 0.3.3.
