### ISSUE TITLE
[Suggestion] Associate specific stories with scenes

### ISSUE THREAD

**Issue by GhostwheelX** [Xbozon/storyteller#14]
At the moment you cannot associate a story with a scene since they don't appear under "scene notes". Might it be possible to do so, so that the story opens (just for the GM) when they activate a specific scene?

**Comment by Xbozon** [comment]
@GhostwheelX 
I took a preliminary look, but I'm not sure it will work out. Alas, history is a different type of object, it's hard to add it there.
