### ISSUE TITLE
[ISSUE] Global sound

### ISSUE THREAD

**Issue by WallaceMcGregor** [Xbozon/storyteller#15]
The latest update with the book opening sound plays a global sound. In other words, any player who opens a journal will "launch" the sound to everyone.

Until now I used a macro to play a sound when someone opened a journal. The last attribute "false" of the macro is intended to prevent it from playing globally. I don't know if it will help you.

`AudioHelper.play({src:"source", volume: 0.8, autoplay: true, loop: false}, **false**)`

**Comment by Xbozon** [comment]
@WallaceMcGregor Yes, you're right, my mistake. Thanks, I'll fix it today!

**Comment by Xbozon** [comment]
@WallaceMcGregor Fixed in Alpha 0.2.1

Thanks again!

**Comment by WallaceMcGregor** [comment]
Thanks to you!
