### ISSUE TITLE
{problem} in V9 DND1.56 there is no tab for stories

### ISSUE THREAD

**Issue by TaleSale** [Xbozon/storyteller#16]
![image](https://user-images.githubusercontent.com/46991962/146906544-fad57544-fe42-4472-9604-b2c30ef45e1e.png)
![image](https://user-images.githubusercontent.com/46991962/146906794-9fe1f175-1ed7-4c07-9d14-bc79d6330fe6.png)

**Comment by Xbozon** [comment]
@TaleSale К сожалению, я пока еще не занимался переносом на v9. Предновогодние недели полны работы :(
Оставьте этот issue открытым, я займусь переводом на v9 в ближайшее время.

**Comment by Xbozon** [comment]
@TaleSale Готово, я портировал на 9 версию. Можете проверить, работает ли у вас?
