### ISSUE TITLE
[Issue] Permission setting.

### ISSUE THREAD

**Issue by WallaceMcGregor** [Xbozon/storyteller#17]
Permission settings do not work. When you right click to assign a permission to players, it is not applied. This is useful for players to have stories always available to read, as a replacement for journal notes. It is a way to get more out of this wonderful module 😇

**Comment by Xbozon** [comment]
@WallaceMcGregor 
Strange, I checked, the resolution appears, however, sometimes you need to refresh the page. Is this the same for you? Is the problem with refreshing the page?

GM:
![image](https://user-images.githubusercontent.com/5074477/148830352-8eaf6206-dea7-4f79-bd5f-5bde551ea9cc.png)
Player:
![image](https://user-images.githubusercontent.com/5074477/148830379-8bcd24ab-5859-4f52-bfd9-f646dbf79c28.png)

**Comment by WallaceMcGregor** [comment]
Ok, I've checked and It's a problem with the module Permission viewer, than do not work with Stories. Sorry for wasting your time 😅

PS: It would be great to allow Stories to be "pinned" on maps like journal notes.

**Comment by Xbozon** [comment]
@WallaceMcGregor 

No problem, it's better to create an issue than to remain silent about a problem.

As for the pins. Unfortunately, it is quite difficult, not in the near future for sure.
