### ISSUE TITLE
Story Link inside Journal

### ISSUE THREAD

**Issue by TioWidow** [Xbozon/storyteller#19]
Hello, Your modification to FoundryVtt is beautiful and very immersive, congratulations.

I'm trying to put the "Stories" link inside a Journal, as in the Image, dragging it into the Journal.

![2022-01-16 02_59_54-Mapa Continental • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/4378980/149649213-87fe1a3a-faf7-4bec-980a-dc5979b61a4f.png)

Am I doing something wrong or is there no such feature yet?

`    @StoryEntry[story17q3glw2874]{Storie Link}
    @JournalEntry[iZD23TNahTpnZ6AQ]{Journal Link}`

**Comment by Xbozon** [comment]
@TioWidow Sorry, StoryEntry is my custom type, it won't be handled this way :(
