### ISSUE TITLE
license

### ISSUE THREAD

**Issue by Benjaneer** [Xbozon/storyteller#21]
please add license info, I would like to use and without terms of use I cannot include in videos (because of the images)

**Comment by Xbozon** [comment]
@Benjaneer 
Is it necessary to specify the license for the module itself or separately for the images used in it?

**Comment by Benjaneer** [comment]
just in the project, so long as the images are also covered by the same terms

**Comment by Xbozon** [comment]
@Benjaneer  It's hard for me to work right now, but I'll try to add more by the weekend

**Comment by Xbozon** [comment]
@Benjaneer 
I apologize for the significant delay, I was forced to relocate. The appropriate license files have been added. Please note the licenses for images and sounds.
