### ISSUE TITLE
Journal Type

### ISSUE THREAD

**Issue by K1llMeNow** [Xbozon/storyteller#22]
I love what you guys have done so far with the project. It really is my favorite way to present information to my players... However, I do a lot of my note taking and organization in normal journal entries.
I know modules like Monk's Enhanced Journal adds types of journal entrees when creating a journal. Is there a way you could copy such a system? (Like the difference between player characters and non player characters). And then it would come with folders and linking capabilities with actors and other journals.

**Comment by Xbozon** [comment]
@K1llMeNow 

Good point. Monk's journal uses a new template system for journals, when I wrote my module, it wasn't there yet :)
Yes, I'm planning to change my module to the new system, but that means rewriting 80% of what's already there. I understand that I wish I had done it sooner, but I should probably look forward to the end of March.

**Comment by K1llMeNow** [comment]
@Xbozon 

Ah. Rewriting absolutely sucks (while I program, I haven't touched foundry yet) - and it's not like you get paid to do this. So I'd understand if you get around to implementing this then (it's not _that_ inconvenient of a issue anyway). I'll still be using it regardless - and thank you for all the work you've done so far!

**Comment by Xbozon** [comment]
@K1llMeNow 
I am happy to say that I managed to rewrite the code after all. Now it is possible to use stories together with standard folders.

**Comment by K1llMeNow** [comment]
<3  thank you so much!
