### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by Benjaneer** [Xbozon/storyteller#24]
I tried creating a link in a journal to a story and it isn't working :(

Table of Contents
Chapter 1
Chapter 2
@StoryEntry[story1c9bg99obfz]{chapter 3}
Appendix A
Appendix B
Appendix C

**Comment by Xbozon** [comment]
@Benjaneer 
This problem comes from this issue https://github.com/Xbozon/storyteller/issues/22, I am in the process of solving it but it will take a long time.
