### ISSUE TITLE
Stories cannot be open 2 times

### ISSUE THREAD

**Issue by Stotorm** [Xbozon/storyteller#27]
Hello, once a story has been opened and closed, it is not possible to reopen it again. The paper sound is activated, but nothing appears anymore. I have to refresh my foundry page to display the story again. Any idea where it coming from ? No error appear on the consol.

**Comment by Xbozon** [comment]
Can you sau version of StoryTeller and FoundryVTT?

**Comment by Xbozon** [comment]
@Stotorm 

I checked the mod's work. Everything works correctly, I have no problem opening the story as many times as I want.
Perhaps a conflict with other mods? Can you check or send a list of mods that you use?

**Comment by Stotorm** [comment]
I checked myself, and the problem seems to come from the module "PF2e Dorako UI", i have desactivate it for now, but maybe you know a solution ?

**Comment by Felipecesarap** [comment]
Same issue here, conflict with the dorako ui module but no errors in the console

**Comment by Xbozon** [comment]
@Stotorm @Felipecesarap 
I am happy to report that this problem should be fixed in the current version 0.4.0. Sorry for the wait!
