### ISSUE TITLE
Show to triggering player

### ISSUE THREAD

**Issue by Steelskinz** [Xbozon/storyteller#3]
Hello,
First of all, I need to say that your work is amazing so far, I really enjoy it. 
My question here is : Is there a way to link it to Monk's Active Tiles Trigger module ( by  in a way that only the person clicking on it  will open the journal. )
 Since 'MATT' module is selecting only journals or actors, is there a macro call that we can use to only open a story ID? By that I mean no " Show to all Players " macro.

**Comment by Xbozon** [comment]
@Steelskinz Thank you so much for the feedback! Yes, I can add a macro method to call the story for a specific player. When I was thinking about this functionality, I couldn't decide how the DM should know when a player has opened a story. Do you have any thoughts?

**Comment by Xbozon** [comment]
I also think this should work too:
```
game.customFolders.stories.entries.get("story1wshuil45t2").sheet.render(true)
```

**Comment by Xbozon** [comment]
@Steelskinz 
The chat option is a good solution. I'll think more about single shows. Keep the issue open.

**Comment by Xbozon** [comment]
@Steelskinz 
Added a short macro:
```
game.StoryTeller.showStoryToPlayerOnly("story1hu5kclu3f7")
```
