### ISSUE TITLE
[IMPORTANT] About the future of this mod

### ISSUE THREAD

**Issue by Xbozon** [Xbozon/storyteller#31]
Unfortunately, the current situation shows that to continue releasing updates and fixes, it is necessary to re-write this mod. I have already made several attempts to do this, but unfortunately I am not able to register a new design style for journal.

If you have any information about this, I would be glad to have your help.

**Comment by brunocalado** [comment]
You could reproduce Monk's Enhanced Journal and let you create a new kind of journal.
![image](https://user-images.githubusercontent.com/4999783/177199039-3f8d2647-e39e-4e93-853c-a9f16f11d17a.png)
https://github.com/ironmonk88/monks-enhanced-journal

You could integrate this module into custom journal. https://github.com/Fair-Strides/FVTT-Custom-Journal-Theming/tree/v9-journals

**Comment by Xbozon** [comment]
@brunocalado 

I think I'm beginning to understand. Thanks for the tip with FVTT-Custom-Journal-Theming, I tried exploring the old version but it didn't work. The new one has a component that I was missing.

```
EntitySheetConfig.updateDefaultSheets(game.settings.get("core", "sheetClasses"));
```

**Comment by Xbozon** [comment]
@brunocalado 
I'm definitely making progress, but I need to work on... little things :D

![image](https://user-images.githubusercontent.com/5074477/177581149-f99c3991-0ad8-421c-9a8d-efd4a6e2ed83.png)

**Comment by brunocalado** [comment]
Do you check out v10? I think this module can be impacted by it. Maybe is good to work on it thinking about v10

**Comment by Xbozon** [comment]
@brunocalado 

Thanks for the recommendation. I checked, thanks to the new system the errors are not very critical. I was able to fix them and the module works. As v10 goes into release, I will update the module.
