### ISSUE TITLE
All Stories have been deleted

### ISSUE THREAD

**Issue by DrAlbee** [Xbozon/storyteller#33]
It appears that the new update has deleted all of the stories I have made. Is there a fix for this? Or do I have to make them all again!?

**Comment by Xbozon** [comment]
@DrAlbee 

Added a restore function from the old settings. Unfortunately, I can't set the new style automatically. The old entries are restored as the old Journal. Please change the Journal Sheet manually :(

![image](https://user-images.githubusercontent.com/5074477/179398083-b3327ea3-e210-486d-845d-7cb626bcf3a7.png)
