### ISSUE TITLE
Journal entries not working: CONST.ENTITY_PERMISSIONS is undefined (V10 incompatibility)

### ISSUE THREAD

**Issue by Tardog** [Xbozon/storyteller#38]
After upgrading to FoundryVTT 10, when attempting to open an existing journal entry, or trying to create a new one - even with the Default Sheet - the action fails, and the following error message is shown in the console:

```
Uncaught TypeError: CONST.ENTITY_PERMISSIONS is undefined
[Detected 1 package: storyteller]
    get defaultOptions <redacted>/modules/storyteller/sheets/story-sheet.js:18
```

Disabling the module restores Journal functionality with the new Pages layout.

**Comment by Xbozon** [comment]
@Tardog 

I'm working as hard as I can, but unfortunately that's not the only problem :(
It will take a week to two weeks, unfortunately.

**Comment by rtschaefer** [comment]
> @Tardog
> 
> I'm working as hard as I can, but unfortunately that's not the only problem :( It will take a week to two weeks, unfortunately.

I just wanted you to know that there are many of us who are grateful for this amazing module, and appreciate the work being done to make it work with other modules and new versions of Foundry.  I am still working with v3.4 which is the last one that seems stable.

**Comment by Tardog** [comment]
> @Tardog
> 
> I'm working as hard as I can, but unfortunately that's not the only problem :( It will take a week to two weeks, unfortunately.

Thank you for putting in all that hard work. The API changes are significant, so I'm not surprised to hear there are more compatibility issues than the one I've reported.

Like the person commenting above me, I love your module, and wanted to express my gratitude for all the energy you put into it.

**Comment by Xbozon** [comment]
Small update due to increased deadlines. I fixed the creation of stories, the only thing left is to fix the saving of text and pictures. I hope to finish in the next few days.

**Comment by Xbozon** [comment]
@Tardog 
I updated storyteller to v10, but temporarily removed the newspaper style. Please check if you have time.
