### ISSUE TITLE
The cover of the book is good, but can I still make an option with the newspaper?

### ISSUE THREAD

**Issue by devinterx** [Xbozon/storyteller#4]

**Comment by Xbozon** [comment]
@devinterx 

There's no technical problem with that, but unfortunately I'm not an artist and can't draw a newspaper. If you have the right materials, without copyright issues, I can try.

**Comment by devinterx** [comment]
OK, I'll draw it on the weekend

**Comment by devinterx** [comment]
@Xbozon source here, copyleft https://drive.google.com/file/d/1_ClDE8jUQ4-kcPtwY0hwxO3jk3TD4yKc/view?usp=sharing

![news-paper-clean](https://user-images.githubusercontent.com/1332516/141656894-ca6c12b3-7c29-4073-9928-b0b885d55346.png)

![news-paper](https://user-images.githubusercontent.com/1332516/141656897-36ff6035-b1b7-4229-8b58-59035def4182.png)

**Comment by devinterx** [comment]
For comparison, book back, waiting for critic...
![news-paperlayout-diff](https://user-images.githubusercontent.com/1332516/141657202-e2c1cb31-afbb-4bd8-ad52-0940111b2193.png)

**Comment by Xbozon** [comment]
@devinterx 
Great job, honestly, you surprised me!

Is the right side still for the image?

**Comment by devinterx** [comment]
@Xbozon i don't really know why you made a place separately for the picture, the editor kind of allows you to insert pictures like html, **for newspapers** it was still more convenient to image: or in the **left side** or **inline**, there is a wish that you make a style for newspapers, with a split into two columns - the rest is small things

**Comment by Xbozon** [comment]
@devinterx 
Only because I was guided by Pathfinder Kingmaker. There's always an image on the right :D
I plan to be able to use editor on both pages. However, I need some break before making big changes. Luckily, adding a new style is a small change.

![image](https://user-images.githubusercontent.com/5074477/141657603-748c50fa-b53f-4baa-aeb6-792e3f8a55eb.png)

**Comment by devinterx** [comment]
@Xbozon they just didn't want to have sex with wrapping text in TextMesh_Pro I went through it, there really made through the ass

**Comment by Xbozon** [comment]
@devinterx 
Tricky move!)

There's still a lot of work to be done (like functioning folders properly), but I think this will be improved as well.

With the new style, I'll probably be done by mid-week.

**Comment by devinterx** [comment]
ok, thx, if something else needs to be drawn (not difficult), you can ask me

**Comment by zeteticl** [comment]
i love the idea of storysteller.
i suggestion that the model allow people change the backgroud by himself.
Then that wouldnt have copyright issues/

**Comment by Xbozon** [comment]
@zeteticl 
Glad to hear that you liked the module. Yes, I plan to add the ability to use my own background images, but for that, I need to make additional settings for indenting from the edges of all page markup. 

I think the newspaper is one of the steps on this feature.

**Comment by Xbozon** [comment]
@devinterx 
Can you add an image mask that will cut off the edges of the image? Like `journal_mask.webp` file. I could do it myself, but it would take time.

**Comment by devinterx** [comment]
@Xbozon I am busy at work until the weekend, i will do, but can you explain where this applies?

**Comment by Xbozon** [comment]
@devinterx No problem, I'll do it myself. I use a black mask image overlaying a simple image, which results in the effect of outlines. In my case, jagged edges. In the case of the newspaper, slightly blurred and rounded.

**Comment by Xbozon** [comment]
@devinterx 
With some limitations, here's what I was able to do:
![image](https://user-images.githubusercontent.com/5074477/142273877-96d5a29c-3275-4294-bd4b-e94fb2811169.png)

**Comment by Xbozon** [comment]
Added in v2.0.0
