### ISSUE TITLE
Cannot Locate the Text Files for my Stories

### ISSUE THREAD

**Issue by rtschaefer** [Xbozon/storyteller#40]
I have created a large quantity of story files, but now I cannot find them no matter where I search.  Can you explain how that work can be retrieved?  I just need the text.

**Comment by Xbozon** [comment]
@rtschaefer Did you upgrade from an older version to a newer one?

**Comment by rtschaefer** [comment]
I am not sure what you are referring to. I am using Foundry v10, but I held onto an older version of Storyteller because I was able to get it to work on Foundry v9.   I am running Foundry through the Forge.

**Comment by Xbozon** [comment]
What version number do you use? Are the stories just gone from the tab or is the whole tab completely gone?

The text will save anyway, I just need to figure out how to help you.

**Comment by rtschaefer** [comment]
I am extremely glad to know the text is still there somewhere. Thank you so much. Many hours of world-building. Whew!

**Comment by rtschaefer** [comment]
I have opened the console. I am not exactly fluent with this stuff. There are a number of red line items.

**Comment by rtschaefer** [comment]
foundry.js:711 ReferenceError: EntitySheetConfig is not defined
[Detected 1 package: storyteller]
    at Object.fn (main.js:68:5)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at Game.setupGame (foundry.js:7826:11)
    at async Game._initializeGameView (foundry.js:8877:5)
    at async Game.initialize (foundry.js:7687:5)

**Comment by Xbozon** [comment]
@rtschaefer That's enough, thank you. I think you accidentally updated to the latest version which does not work with v10, can you check?
The version with a separate tab should be Storyteller 0.3.4

**Comment by rtschaefer** [comment]
Yeah, 3.4 was what I was using before and I upgraded out of desperation to see if it will work LOL.  I will change to 3.4 right away and check

**Comment by rtschaefer** [comment]
Using 3.4 and the stories tab is still gone. Hmmm

**Comment by Xbozon** [comment]
@rtschaefer Have the console messages changed?

**Comment by rtschaefer** [comment]
I am not able to find anything really. I was able to use the filter to find storyteller in the console but now...nothing

**Comment by Xbozon** [comment]
![image](https://user-images.githubusercontent.com/5074477/190297326-9c1eda15-f205-4a1e-80a7-23ee35b29e48.png)

**Comment by rtschaefer** [comment]
rebooted and loaded. Found only this line

foundry.js:6693 Foundry VTT | Loaded localization file https://assets.forge-vtt.com/bazaar/modules/storyteller/0.3.4/lang/en.json

**Comment by rtschaefer** [comment]
{
  "I18N.MAINTAINERS": ["Xbozon"],

  "DOCUMENT.StoryEntry": "Story",
  "JOURNAL.ActionConfigure": "Configure",

  "STORYTELLER.CopyID": "Copy story ID",
  "STORYTELLER.Journal": "Journals",
  "STORYTELLER.Stories": "Stories",
  "STORYTELLER.ChangeImage": "Click here to change image",
  "STORYTELLER.CantCreateFolder": "Folder creation is not currently supported, wait for future updates! Thanks for understanding!",
  "STORYTELLER.BookOpenSound": "Enable book opening sound",
  "STORYTELLER.BookOpenSoundHint": "For each user individually",
  "STORYTELLER.StoryName": "Story name:",

  "STORYTELLER.Settings.Theme": "Change the style of the story",
  "STORYTELLER.Settings.ThemeHint": "Changes the theme for all players",
  "STORYTELLER.Settings.ThemeBook": "Book",
  "STORYTELLER.Settings.ThemeNewspaper": "Newspaper",
  "STORYTELLER.Settings.Size": "The size of the story on the screen",
  "STORYTELLER.Settings.SizeHint": "100% takes up almost the entire screen height, 80% takes up no more than 80% of the screen height"

**Comment by Xbozon** [comment]
Two ways:
1) Wait for the weekend, I think to finish the update over the weekend.
2) Pull out the old stories manually. It's a little confusing, but not hard, here are the instructions:

![image](https://user-images.githubusercontent.com/5074477/190297957-1d788ac3-17e9-403e-afd1-a18fb9d62795.png)

**Comment by Xbozon** [comment]
Open the console, enter the following text in the ">" field and press enter.

game.settings.get('storyteller', 'storiesEntries')

In the drop-down list you can find all the information about your stories.

Not very convenient, but safe.

**Comment by rtschaefer** [comment]
Where do I find a place to "enter" stuff into the console.  I only see a filter field.

**Comment by Xbozon** [comment]
Here:

![image](https://user-images.githubusercontent.com/5074477/190298636-24a2e9d1-96ae-4e5c-9727-1e76234a3cc9.png)

**Comment by rtschaefer** [comment]
This is what I get back 

game.settings.get('storyteller', 'storiesEntries')
foundry.js:2721 Uncaught Error: This is not a registered game setting
[No packages detected]
    at ClientSettings.get (foundry.js:2721:42)
    at <anonymous>:1:15

**Comment by Xbozon** [comment]
You have disabled a module in the modification list 

C:

**Comment by rtschaefer** [comment]
Okay so what modules do I need to enable? Storyteller is active. So there is a conflict?  (sorry I am not more versed in this stuff).

**Comment by Xbozon** [comment]
@rtschaefer 
Very strange, because this error occurs only if the module was not enabled. Maybe you need to restart your world somehow.
Don't worry about questions, we're doing all we can :)

**Comment by rtschaefer** [comment]
Okay, I will restart Foundry and see what happens.  Thank you.

**Comment by rtschaefer** [comment]
ame.settings.get('storyteller', 'storiesEntries')
foundry.js:2721 Uncaught Error: This is not a registered game setting
[No packages detected]
    at ClientSettings.get (foundry.js:2721:42)
    at <anonymous>:1:15

**Comment by rtschaefer** [comment]
I am not seeing any errors related to Storyteller. There are a good number of other errors that I am already living with (version 10 is a love/hate thing so far.  

If only I could locate the text, I'd be in tall cotton for Friday night.

**Comment by rtschaefer** [comment]
Weird. When I went to v3.4  and rebooted my server. Now Storyteller is turned on, but it now does not even appear in my Game Settings (where you can change the size of the stories, go from book to newspaper, turn page sound on/off, etc.).  Very strange.

**Comment by Xbozon** [comment]
Time for rough action :D
1) Turn off storyteller completely.
2) Open the console, check that the error is still there
```
game.settings.get('storyteller', 'storiesEntries')
```
3) Insert and execute this code:
```
game.settings.register('storyteller', 'storiesEntries', {
        scope: 'world',
        config: false,
        type: Object,
        default: {}
    })
```

4) Call game.settings.get('storyteller', 'storiesEntries') again

![image](https://user-images.githubusercontent.com/5074477/190300929-14f86952-4172-4d69-ba13-21d5a088b05e.png)

**Comment by Xbozon** [comment]
@rtschaefer You are using a very old version, I'm surprised anything ever worked

**Comment by rtschaefer** [comment]
game.settings.register('storyteller', 'storiesEntries', {
        scope: 'world',
        config: false,
        type: Object,
        default: {}
    })
undefined

**Comment by rtschaefer** [comment]
I then re-entered 

game.settings.get('storyteller', 'storiesEntries')

No error came back, but when I turned the module back on.... same error comes back.

**Comment by Xbozon** [comment]
This does not fix the module itself, but only displays a list of saved stories, look carefully at the screenshots.

**Comment by Xbozon** [comment]
Right now the module is not working in v10 and I haven't finished the update yet.

**Comment by Xbozon** [comment]
@rtschaefer 
I updated storyteller to v10, but temporarily removed the newspaper style. Please check if you have time.
