### ISSUE TITLE
Can't add image on right side.

### ISSUE THREAD

**Issue by Babipoki** [Xbozon/storyteller#42]
Yo! Love storyteller and THANK YOU for updating for V10! It works fine except I can't add the image to the right side. 

It kinda looks like this:

![image](https://user-images.githubusercontent.com/13620623/193627902-745dd324-a52c-4d79-80ac-ff89fb9fc027.png)

I remember in previous versions (and pre-V10) there was this box on the right where you could drop the pictures in there, now that box is gone. Could it be one of my modules? Here's what I have:

![image](https://user-images.githubusercontent.com/13620623/193628137-daea43c8-424c-40a1-aff3-a32770433446.png)
![image](https://user-images.githubusercontent.com/13620623/193628191-b0e8d09f-68c4-4109-9b1c-a4fada14352a.png)

**Comment by Xbozon** [comment]
@Babipoki 

Turn the page to the table of contents, add a new page with the image type. You can now create a large number of pages and images.

**Comment by Babipoki** [comment]
I see! Is there a way to not include page title in a new page?

**Comment by Xbozon** [comment]
Yes, if you open page editing, there is an option to remove the header
