### ISSUE TITLE
Storyteller for PF2e in v10 causes canvas to not load.

### ISSUE THREAD

**Issue by joshscorcher** [Xbozon/storyteller#43]
I have all modules deactivated, but for some reason Storyteller causes a blank canvas and is throwing a million errors. I am on the latest version of PF2e and am on the latest version of V10.

The big error I get at the top is "Canvas Drawing Failed; This is not a registered game setting."

**Comment by Xbozon** [comment]
Hello. Can you please send a screenshot of the error?

**Comment by joshscorcher** [comment]
![image](https://user-images.githubusercontent.com/52643998/194383580-d9535ad6-4d05-45db-b1a5-4daceae007e0.png)
[Storyteller Error Console Log.txt](https://github.com/Xbozon/storyteller/files/9727321/Storyteller.Error.Console.Log.txt)

**Comment by Xbozon** [comment]
Very strange, because there are no errors from the storyteller side. If you turn it off, do the errors disappear?

**Comment by joshscorcher** [comment]
Disabling all modules does not not throw any errors.

**Comment by Xbozon** [comment]
I guess the mistake was in the foundry itself. I could not replicate it, if it suddenly appears again, please reopen the issue.
