### ISSUE TITLE
Incompatibility with MidiQOL

### ISSUE THREAD

**Issue by republicadorpgdm20** [Xbozon/storyteller#44]
Hi, I recently updated Foundry VTT to V10 and noticed that this module is breaking MIDIQOL automations.
I did several tests to make sure and I was able to confirm this, is there anything I can do to fix it? Did you get any other problems like this?
If can fix it, it would be really cool!!

**Comment by Xbozon** [comment]
@republicadorpgdm20 

I apologize for not posting earlier, this problem was fixed along with config.DEBUG.

Thanks for using the module!
