### ISSUE TITLE
Beta display error

### ISSUE THREAD

**Issue by thangurion** [Xbozon/storyteller#45]
Hi, 

first of all, thank you for this excellent module. The new possibilities of the beta are great.

I have a display error:
- The background of the book is gray and not transparent.

an some wishes:
- For my use, it would be better if the articles were not automatically numbered (but don't know if others see it that way). 
- It would also be nice to be able to choose whether a page should appear on the frontpage or not.
Greetings
Peter

**Comment by Xbozon** [comment]
@thangurion 
Hi! Could you please attach screenshots, I don't quite understand the problem.

**Comment by thangurion** [comment]
Hi,
I just checked it in the inspector from Firefox. The problem occurs in connection with Monk's little details. This makes a frame around the journal. 
![Screenshot 2022-10-20 184418](https://user-images.githubusercontent.com/113504992/197009231-f5ad2532-7776-49e6-8fa6-2fd106a5cea5.png)

**Comment by Xbozon** [comment]
@thangurion 

I apologize for the long response on this problem. I have now updated everything to the latest versions and checked, apparently this problem no longer exists. 

If suddenly, it is still present, please reopen the issue. Until then, I will close it.

Thanks for using my mod!

**Comment by Xbozon** [comment]
@thangurion 

This sounds silly, but after the post above, the problem showed up. I fixed it in v1.0.3, please update.
