### ISSUE TITLE
Change CONFIG.debug to boolean breaks a lot of modules

### ISSUE THREAD

**Issue by MrPrimate** [Xbozon/storyteller#46]
You set `CONFIG.debug = true` at https://github.com/Xbozon/storyteller/blob/main/main.js#L3

`CONFIG.debug` is an object, changing it to a bool breaks a lot of modules that add their own debug settings here. Use a key within this object instead.

You also, probably don't want to be shipping debug  set to true in a module.

**Comment by kaelad02** [comment]
I wouldn't be surprised if this is the underlying cause of #44

**Comment by Xbozon** [comment]
@MrPrimate 
I really apologize for this silly mistake, I was finishing very tired and forgot to put away the debugging. Thanks for creating the issue!

Fixed in v1.0.1
