### ISSUE TITLE
Display error on V9

### ISSUE THREAD

**Issue by WallaceMcGregor** [Xbozon/storyteller#48]
Hi

After the last updates (I can't say wich of one) the display of the storyteller journal is broken. It's happens on new and old (😢) journal entries.

I am on the 9.280 version of Foundry.

![chrome_2VDusnGHEv](https://user-images.githubusercontent.com/17795541/197252096-c977c3cd-5e95-4d53-8f34-a076714c020f.jpg)

**Comment by Xbozon** [comment]
@WallaceMcGregor 

I have an assumption that you are using the v10 version of the module, in Foundry v9. 

Can you show the current version of the installed storyteller?

**Comment by WallaceMcGregor** [comment]
Right now it is on version 1.0.2. At the time of the screenshot it would be a lower version.

I think it has been updating even though I am still on Foundry v9.

**Comment by Xbozon** [comment]
Unfortunately, the old log for v9 is only supported in the Alpha 0.4.1 version. Since version 1.0.0, only Foundry V10 is supported.
This is due to the addition of multi-page journals.

**Comment by WallaceMcGregor** [comment]
Ok. I'll try to downgrade to that version (or I'll wait until finishing my actual games to upgrade Foundry to v10 😅).

Thanks.

**Comment by Xbozon** [comment]
@WallaceMcGregor 

Okay, feel free to write me if you have any problems.
