### ISSUE TITLE
"add new page" button is pushed below visible area when adding 15+ pages

### ISSUE THREAD

**Issue by daved181** [Xbozon/storyteller#49]
When adding to many pages the button to add more is pushed below the page and can't be clicked. I'm on version 10 build 286.
Have a lot of modules installed however none that interferes with journals (to my knowledge).

![bug](https://user-images.githubusercontent.com/93661194/197372292-b3e1f5b2-279b-4121-bc27-56f657774c62.png)

**Comment by Xbozon** [comment]
@daved181 
Indeed. It's not hard to fix, I'll try in the near future.

**Comment by daved181** [comment]
@Xbozon 
Thanks :)

**Comment by daved181** [comment]
kinda fixed it myself by adding a scrollbar to pages in storyteller.css

.page{
    overflow:scroll;
    overflow-x:hidden;
}

**Comment by Xbozon** [comment]
@daved181 
I added support for scroll in v1.0.3, please update. You can turn it on in the settings, as the design is far from perfect yet.
