### ISSUE TITLE
Not opening after a certain condition ? 

### ISSUE THREAD

**Issue by Steelskinz** [Xbozon/storyteller#5]
Let me explain : 
- When I stay for too long inactive (I think?) it happens
- Will work if I F5 the page.
- Impossible to actually reach the Stories tab and it spams me this in the console : 
![image](https://user-images.githubusercontent.com/93941729/140843687-6c1d8ba1-9bba-4aa2-85da-b80e3fe01556.png)

**Comment by Xbozon** [comment]
@Steelskinz 

Fixed the output in the console, I forgot to turn off debug mode. 
As for the tab, I'm still have random problems and can't catch them all. It would be ideal if you could record a short video of when the stories tab is no longer active. It will help a lot.

**Comment by Xbozon** [comment]
@Steelskinz 
I found out the main bug. If you open the history, switch the tab from journals, to (for example) chat, and closing the history - story tab is blocked.

I fix it in v0.2.2
