### ISSUE TITLE
[Improvement suggestion] Stories pin

### ISSUE THREAD

**Issue by lucaspicerni** [Xbozon/storyteller#50]
Implement the possibility to create stories pins on the canvas, as you can do with journals.

**Comment by Xbozon** [comment]
@lucaspicerni 
But it's already possible.
![image](https://user-images.githubusercontent.com/5074477/197374996-b6f38db8-b566-4c50-88c5-b7616bf86cc7.png)

**Comment by lucaspicerni** [comment]
I believe I have found the real source of the problem. For some reason, even though I'm still on Foundry version 9, the module has updated to the latest version, compatible with V10. In fact the whole module is no longer working for me and I am not able to downgrade the version.

**Comment by lucaspicerni** [comment]
It was actually a mix of many issues, one of them being the module's incompatibility with Monk Enhanced Journal. My mistake, sorry.
