### ISSUE TITLE
cannot scroll longer journal entries

### ISSUE THREAD

**Issue by MrVauxs** [Xbozon/storyteller#52]
- Foundry 10.288
- Pathfinder 4.3.1
- Storyteller 1.0.1

![image](https://user-images.githubusercontent.com/32039708/198745600-0047315b-5fcc-4707-b599-a2f243bd1437.png)

**Comment by Geektasticdad** [comment]
This issue is the only reason I don't use Storyteller, I have some long descriptions in some of my campaign notes. If I create a new page, then it shows up in the index. Beautiful module, but this is a deal breaker for me unfortunately.

**Comment by Xbozon** [comment]
@Geektasticdad 

I am already working on an update to fix some of the bugs that have accumulated. I think you can expect a solution around January 5th.

**Comment by Xbozon** [comment]
@MrVauxs @Geektasticdad 
I added support for scroll in v1.0.3, please update. You can turn it on in the settings, as the design is far from perfect yet.
