### ISSUE TITLE
Can't link to specific pages within a story to only one player

### ISSUE THREAD

**Issue by Sternss0n** [Xbozon/storyteller#53]
Hey!

Trying to make a trigger tile that opens a specific page of a story sheet for the triggering player. Is that possible with the current tools?

**Comment by Xbozon** [comment]
@Sternss0n 

Sorry for the long reply, yes, it is possible. Use the showStoryToPlayerOnly method instead of the normal showStoryByIDToAll.

Sorry I didn't add it to ReadMe

```
game.StoryTeller.showStoryByIDToAll("qoWx7HNFZN1jgECs")
```
```
game.StoryTeller.showStoryToPlayerOnly("qoWx7HNFZN1jgECs")
```
