### ISSUE TITLE
Can't Change Name in v10

### ISSUE THREAD

**Issue by GhostwheelX** [Xbozon/storyteller#54]
After updating to v10, I'm unable to change the journal name for stories unfortunately.

**Comment by Xbozon** [comment]
![image](https://user-images.githubusercontent.com/5074477/210354043-b30df688-3697-4821-b041-aaccb92f7ee7.png)


I apologize for the long response. The rename function has been moved to this field.

Thanks for using the mod, feel free to write if you have any problems.
