### ISSUE TITLE
[BUG] Missing New story button, missing new page button

### ISSUE THREAD

**Issue by ArdonDaros** [Xbozon/storyteller#59]
Tested on Foundry version 9, build 269

Tested Storytellers:
- 0.3.3
- 0.3.4
- 0.4.0
- 0.4.1
- 1.0.0
- 1.0.1
- 1.0.3

None of the above versions had "new page button" or "new story button". Are these old features that no longer exist in any build?

Screenshot:
https://imgur.com/a/x4c2Bqr

**Comment by Xbozon** [comment]
@ArdonDaros 
I suspect that you are using an old version of the mod with a relatively new version of foundry. In that case, the mod may not work correctly.

From version 1.0.0 only foundry v10 and higher is supported.

**Comment by Xbozon** [comment]
When you use the latest version, you should have a way to create history through the create journal button.
