### ISSUE TITLE
Turning pages function will be really helpful

### ISSUE THREAD

**Issue by bnp800** [Xbozon/storyteller#6]
It will be nice to have the function to turn pages like a real book, changing to another story with animation!

**Comment by Xbozon** [comment]
@bnp800 
Is it the page-flipping animation that's important, or is it something like a "Next Page" button?

**Comment by bnp800** [comment]
A "Next page" button will do, but even better with page-flipping animation.

**Comment by Xbozon** [comment]
@bnp800 
Next button planned, I will add. Unfortunately, it's hard to expect any work with animation this year. Maybe I can start in 2022.

**Comment by Benjaneer** [comment]
https://github.com/Xbozon/storyteller/pull/39

**Comment by Xbozon** [comment]
@bnp800 

Unexpectedly, I added the page turning function :)
