### ISSUE TITLE
Update to foundryvtt v11

### ISSUE THREAD

**Issue by jakezarakki** [Xbozon/storyteller#62]
I would like to know if there will be an update for the foundryvtt  v11

**Comment by Xbozon** [comment]
Unfortunately, it hasn't worked out yet. The basic functionality works, but the story is not added to the creation menu. Have to wait until next week :(

**Comment by Xbozon** [comment]
@jakezarakki I updated it. Please give it a try.

**Comment by jakezarakki** [comment]
THX!!!! Its works!!! REALLY REALLY THX
