### ISSUE TITLE
Scroll option locks up Forge

### ISSUE THREAD

**Issue by Lyinggod** [Xbozon/storyteller#63]
When the beta scroll text option is selected, after re-load of screen, Forge hangs with a "your system is taking a long time to load" error that never seems to resolve.

System: FFG Star Wars 1.801
Forge: 10.291

**Comment by Xbozon** [comment]
@Lyinggod 

I apologize for the incredibly long reply, I have not been able to replicate the problem, but just in case, I have changed the way this setting is set up.

It might be working now. I would appreciate it if you could check if this is still relevant :(
