### ISSUE TITLE
Bug in the console 

### ISSUE THREAD

**Issue by Fridan99** [Xbozon/storyteller#65]
Foundry v11.311

Dnd5e System 2.3.1

Storyteller 1.1.0

Other modules deactivated: NO

**Decription of the bug**

I haven't noticed anything unusual, this message appears in the console when I try to run a survival roll macro from item macro. 

Probably there is some kind of conflict. 

Image of the console

![1 11](https://github.com/Xbozon/storyteller/assets/86131373/0bf0a053-4e87-4e03-a1f6-2156ce3931ee)

**Comment by Xbozon** [comment]
I couldn't replicate the same error as I don't know what modules you have installed, however I have corrected the code a bit, it probably won't occur again.

Thank you very much for the bug report!
