### ISSUE TITLE
No single sheet option

### ISSUE THREAD

**Issue by mfozz** [Xbozon/storyteller#66]
I can't seem to choose the single sheet option anymore. The only option I've been able to create is the full journal book. The help image (step-1.webp) shows a step 5 with the single sheet popped out. I'm not sure whether the steps are missing in the documentation or whether it's a bug.
v11

**Comment by Xbozon** [comment]
@mfozz 

Yes, there is no more one-page template, however you can create a book, add 2 sheets to it and it will give exactly the same effect. When you click "show", the book will open on the right page in the players.
