### ISSUE TITLE
Request: Integration with Monk's Active Tiles Mod

### ISSUE THREAD

**Issue by abominablerob** [Xbozon/storyteller#7]
Being able to open a story when a character enters a tile or clicks on one would be super useful and cool. It would also sidestep the need for macros. Currently Monk's Active Tiles doesn't allow selection of Stories as action (there is one for opening character or Journal Note).
Having this there would be awesome. 
Thanks and great work!

**Comment by Xbozon** [comment]
@abominablerob 
Good issue, I understand your need. Unfortunately, I cannot somehow add this feature to Monk's Active Tiles, I have tried. I see that you have created an issue with the developer of this mod, one can only rely on him. Until then, I can only recommend using the macro call as a universal solution (that's what it's made for)
