### ISSUE TITLE
Cannot change story name

### ISSUE THREAD

**Issue by GhostwheelX** [Xbozon/storyteller#9]
I can't find a way to change the name of the journal story entry; I've tried right-clicking on it in the journal, and I've clicked on the title when it was open, and neither option worked. Is there a way to do so?

**Comment by Xbozon** [comment]
@GhostwheelX 
Working on it right now, will add it this week!

**Comment by Xbozon** [comment]
![image](https://user-images.githubusercontent.com/5074477/143303352-9ad6655d-74cd-495d-a2ca-8ed8f12bbcec.png)

Added in v2.0.0
